"""tabla imagenes

Revision ID: 0c696869ab4d
Revises: d0c7b8e4b57c
Create Date: 2025-05-06 13:57:06.776918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c696869ab4d'
down_revision = 'd0c7b8e4b57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_conversion_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=250), nullable=True),
    sa.Column('red_pixels', sa.Integer(), nullable=True),
    sa.Column('green_pixels', sa.Integer(), nullable=True),
    sa.Column('blue_pixels', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('image_path', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_conversion_result')
    # ### end Alembic commands ###
